// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT-Vlgwm5b3gmx_r99Y4YQZg4ONzshE5Q',
    appId: '1:1072454452230:web:7416f37b9bff78c25e6f87',
    messagingSenderId: '1072454452230',
    projectId: 'fire-auth-otp-5781c',
    authDomain: 'fire-auth-otp-5781c.firebaseapp.com',
    storageBucket: 'fire-auth-otp-5781c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPTwy2NrSPUTCJQJBWMmOltQpPuPGiKU',
    appId: '1:1072454452230:android:b2608dc1f1c490965e6f87',
    messagingSenderId: '1072454452230',
    projectId: 'fire-auth-otp-5781c',
    storageBucket: 'fire-auth-otp-5781c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQsUhdyfaUYsw12bz2g5xR63nOYEbIkM',
    appId: '1:1072454452230:ios:7ad1ba32749280c95e6f87',
    messagingSenderId: '1072454452230',
    projectId: 'fire-auth-otp-5781c',
    storageBucket: 'fire-auth-otp-5781c.appspot.com',
    iosClientId: '1072454452230-st9pid0k84ep17goktit3646tudtk8tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAuthOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQsUhdyfaUYsw12bz2g5xR63nOYEbIkM',
    appId: '1:1072454452230:ios:e1de64a2cf3085a65e6f87',
    messagingSenderId: '1072454452230',
    projectId: 'fire-auth-otp-5781c',
    storageBucket: 'fire-auth-otp-5781c.appspot.com',
    iosClientId: '1072454452230-vtdjc1srj4feji1u6qngh0vedg8r01co.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAuthOtp.RunnerTests',
  );
}
